name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-deps:
    name: Install Dependencies (Cache Lookup Only)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/configure-nodejs
        with:
          lookup-only: 'true'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/configure-nodejs
      - name: Build
        run: npm run build
      - name: Package the Construct
        run: |
          npm run compile -w packages/cdk-construct
          npm run post-compile -w packages/cdk-construct
          npm run test -w packages/cdk-construct
          npm run package -w packages/cdk-construct
      - name: Upload cdk-construct-package artifact
        uses: actions/upload-artifact@v4
        with:
          name: cdk-construct-package
          path: packages/cdk-construct/dist/js/*.tgz

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/configure-nodejs
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/builder-writeRole
          aws-region: us-east-2

      - name: Build
        run: |
          npm run build

      - name: Deploy CDK Stack (Main)
        if: github.ref == 'refs/heads/main'
        run: |
          npx cdk deploy crush-test --require-approval never --outputs-file cdk-outputs.json

      - name: Deploy CDK Stack (PR)
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          npx cdk deploy crush-test-pr-${PR_NUMBER} --require-approval never --outputs-file cdk-outputs.json

  deploy-packaged:
    name: Deploy Packaged
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    steps:
      - name: Checkout CDK only (sparse)
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            cdk-consumer-test
          sparse-checkout-cone-mode: false

      - name: Download cdk-construct-package artifact
        uses: actions/download-artifact@v4
        with:
          name: cdk-construct-package
          path: cdk-consumer-test

      - name: Install packaged construct
        working-directory: cdk-consumer-test
        run: |
          npm install ./crush-test-cdk*.tgz

      - name: Build
        working-directory: cdk-consumer-test
        run: |
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/builder-writeRole
          aws-region: us-east-2

      - name: Deploy CDK Stack (Main)
        if: github.ref == 'refs/heads/main'
        working-directory: cdk-consumer-test
        run: |
          npx cdk deploy crush-test-construct-test --require-approval never --outputs-file cdk-outputs.json

      - name: Deploy CDK Stack (PR)
        if: github.event_name == 'pull_request'
        working-directory: cdk-consumer-test
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          npx cdk deploy crush-test-construct-test-pr-${PR_NUMBER} --require-approval never --outputs-file cdk-outputs.json
